name = 'TTMenus Client Menu'
license = 'MIT'
licenselink = 'https://github.com/anomrac21/_menus_ttms/LICENSE'
description = 'Displays all content on a client menu'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/anomrac21/_menus_ttms'

# If you have a running demo of the theme
demosite = 'https://anomrac21.github.io/_menus_ttms'

# Taxonomy terms
tags = ['menu', 'promotions']
features = ['odoo', 'ttmenus', 'payments']

# If the theme has multiple authors
authors = [
  {name = 'anomrac21', homepage = 'https://github.com/anomrac21'}
]

# If the theme has a single author
[author]
  name = 'anomrac21'
  homepage = 'https://github.com/anomrac21'

# If porting an existing theme
[original]
  author = 'anomrac21'
  homepage = 'https://github.com/anomrac21'
  repo = 'https://github.com/anomrac21/_menus_ttms'
